### PR TITLE
Fix example parameters for "--column" to be valid jsonpaths

### PR DESCRIPTION
**Pull request by haakonstorm**
"entity_name changed" to "entity_id"
"attributes.friendly_name" changed to "name"

### CODE REVIEW

**Comment by homeassistant** [comment]
Hello @haakonstorm,

When attempting to inspect the commits of your pull request for CLA signature status among all authors we encountered commit(s) which were not linked to a GitHub account, thus not allowing us to determine their status(es).

The commits that are missing a linked GitHub account are the following:

- [`78b237603087112996b9f7d8dd90f57f54e15b10`](https:&#x2F;&#x2F;github.com&#x2F;home-assistant&#x2F;home-assistant-cli&#x2F;pull&#x2F;303&#x2F;commits&#x2F;78b237603087112996b9f7d8dd90f57f54e15b10) - This commit has something that looks like an email address (storm@10core.local). Maybe try linking that to GitHub?.

Unfortunately, **we are unable to accept this pull request until this situation is corrected.**

Here are your options:

1. If you had an email address set for the commit that simply wasn't linked to your GitHub account you can link that email now and it will retroactively apply to your commits. The simplest way to do this is to click the link to one of the above commits and look for a blue question mark in a blue circle in the top left. Hovering over that bubble will show you what email address you used. Clicking on that button will take you to your email address settings on GitHub. Just add the email address on that page and you're all set. GitHub has more information about this option [in their help center](https://help.github.com/articles/setting-your-email-in-git/#commits-on-github-arent-linking-to-my-account).

2. If you didn't use an email address at all, it was an invalid email, or it's one you can't link to your GitHub, you will need to change the authorship information of the commit and your global Git settings so this doesn't happen again going forward. GitHub provides some great instructions on how to change your authorship information [in their help center](https://help.github.com/articles/setting-your-email-in-git/).
   * If you only made a single commit you should be able to run
      ```
      git commit --amend --author="Author Name <email@address.com>"
      ```
      (substituting Author Name and email@address.com for your actual information) to set the authorship information.
   * If you made more than one commit and the commit with the missing authorship information is not the most recent one you have two options:
       1. You can re-create all commits missing authorship information. This is going to be the easiest solution for developers that aren't extremely confident in their Git and command line skills.
       2. You can use [this script](https://help.github.com/articles/changing-author-info/) that GitHub provides to rewrite history. **Please note:** this should be used only if you are very confident in your abilities and understand its impacts.
   * Whichever method you choose, I will come by to re-check the pull request once you push the fixes to this branch.

We apologize for this inconvenience, especially since it usually bites new contributors to Home Assistant. We hope you understand the need for us to protect ourselves and the great community we all have built legally. The best thing to come out of this is that you only need to fix this once and it benefits the entire Home Assistant and GitHub community.

Thanks, I look forward to checking this PR again soon! :heart:

**Comment by homeassistant** [comment]
Hello @haakonstorm,

When attempting to inspect the commits of your pull request for CLA signature status among all authors we encountered commit(s) which were not linked to a GitHub account, thus not allowing us to determine their status(es).

The commits that are missing a linked GitHub account are the following:

- [`78b237603087112996b9f7d8dd90f57f54e15b10`](https:&#x2F;&#x2F;github.com&#x2F;home-assistant&#x2F;home-assistant-cli&#x2F;pull&#x2F;303&#x2F;commits&#x2F;78b237603087112996b9f7d8dd90f57f54e15b10) - This commit has something that looks like an email address (storm@10core.local). Maybe try linking that to GitHub?.

Unfortunately, **we are unable to accept this pull request until this situation is corrected.**

Here are your options:

1. If you had an email address set for the commit that simply wasn't linked to your GitHub account you can link that email now and it will retroactively apply to your commits. The simplest way to do this is to click the link to one of the above commits and look for a blue question mark in a blue circle in the top left. Hovering over that bubble will show you what email address you used. Clicking on that button will take you to your email address settings on GitHub. Just add the email address on that page and you're all set. GitHub has more information about this option [in their help center](https://help.github.com/articles/setting-your-email-in-git/#commits-on-github-arent-linking-to-my-account).

2. If you didn't use an email address at all, it was an invalid email, or it's one you can't link to your GitHub, you will need to change the authorship information of the commit and your global Git settings so this doesn't happen again going forward. GitHub provides some great instructions on how to change your authorship information [in their help center](https://help.github.com/articles/setting-your-email-in-git/).
   * If you only made a single commit you should be able to run
      ```
      git commit --amend --author="Author Name <email@address.com>"
      ```
      (substituting Author Name and email@address.com for your actual information) to set the authorship information.
   * If you made more than one commit and the commit with the missing authorship information is not the most recent one you have two options:
       1. You can re-create all commits missing authorship information. This is going to be the easiest solution for developers that aren't extremely confident in their Git and command line skills.
       2. You can use [this script](https://help.github.com/articles/changing-author-info/) that GitHub provides to rewrite history. **Please note:** this should be used only if you are very confident in your abilities and understand its impacts.
   * Whichever method you choose, I will come by to re-check the pull request once you push the fixes to this branch.

We apologize for this inconvenience, especially since it usually bites new contributors to Home Assistant. We hope you understand the need for us to protect ourselves and the great community we all have built legally. The best thing to come out of this is that you only need to fix this once and it benefits the entire Home Assistant and GitHub community.

Thanks, I look forward to checking this PR again soon! :heart:

**Comment by maxandersen** [comment]
@haakonstorm thanks for the fix but please try and fix your committer email. use `git config --global user.email` for that.

That said, what version of homeassistant are you using where `attributes.friendly_name` been renamed to `name` ?

**Comment by haakonstorm** [comment]
(Yes, sorry, I'm new to collaborating with pull requests, and there is something snafu with my config in between git, zsh, gitkraken and github desktop; my user.email is good, there is something else. Working on it. )

Regarding the rename, I'm running latest HA (actually, same error on latest and two deltas back as I just upgraded now and same results). 

See this output:

```
❯ hass-cli --server https://s89.duckdns.org --token mytokentokentoken --output table --insecure --sort-by last_changed --columns "ENTITY=entity_id, NAME=name" entity list
ENTITY                                                 NAME
media_player.downstairs                               None
media_player.upstairs                                 SONOS SOV
sensor.daylight                                       None
light.light_14                                        Vaskerom
light.light_4                                         Gang inngang
light.light_5                                         Gang bad
light.light_6                                         Gang inngang2 Natt
light.light_7                                         Disco 3
binary_sensor.tradfri_motion_sensor_3                 Motion Oppe
binary_sensor.tradfri_motion_sensor_4                 Motion Gang
sensor.stormpadpro_battery_state                      None
sensor.stormpadpro_battery_level                      None
sensor.fsm_state_gangen_dagtid                        None
sensor.remote_kjokken_battery_level                   None
sensor.fsm_state_gangen_nattestid                     None
sensor.remote_gang_battery_level                      None



❯ hass-cli --server https://s89.duckdns.org --token mytokentokentoken.31eBVf7dli791LZD0RjJLWhTG9EDgbWgDaiVg9AayU4 --output table --insecure --sort-by last_changed --columns "ENTITY=entity_name, NAME=attributes.friendly_name" entity list
ENTITY     NAME













(empty output)
```


This is latest HA via HASSIO running on RPI3B+, same results on RPI4 4GB, just tried. 
I'm on zsh, on macOS Catalina latest beta. Might be related?

**Comment by maxandersen** [comment]
ah you are using "entity list" not "state list". 

okey, entity list is kinda using "internal api" which *might* have changed recently - I haven't followed that so closely.

"state list" still has `attributes.friendly_name`. 

With respect to `entity_name` that has changed or it was original a typo (can't remember :)
Will you open a new PR with the fixes and proper email refs ?

**Comment by maxandersen** [comment]
duplicating https://github.com/home-assistant/home-assistant-cli/pull/305

**Pull request closed without merging**
